const fs = require('fs');
const path = require('path');

// Configuration
const BASE_URL = 'https://ai-news-br.vercel.app';
const DATES_FILE = path.join(__dirname, 'available-dates.json');
const SITEMAP_FILE = path.join(__dirname, 'sitemap.xml');
const INDEX_FILE = path.join(__dirname, 'index.html'); // Added index.html reference

try {
    // 1. Read the array of dates
    const datesData = fs.readFileSync(DATES_FILE, 'utf8');
    const dates = JSON.parse(datesData);

    if (dates.length === 0) throw new Error("No dates found in JSON");

    const latestDate = dates[0]; // The newest date generated by zo.computer

    // ==========================================
    // PART 1: GENERATE SITEMAP
    // ==========================================
    let sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    sitemapContent += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    sitemapContent += `   <url>\n`;
    sitemapContent += `      <loc>${BASE_URL}/</loc>\n`;
    sitemapContent += `      <lastmod>${latestDate}</lastmod>\n`;
    sitemapContent += `      <changefreq>daily</changefreq>\n`;
    sitemapContent += `      <priority>1.0</priority>\n`;
    sitemapContent += `   </url>\n`;

    dates.forEach(date => {
        sitemapContent += `   <url>\n`;
        sitemapContent += `      <loc>${BASE_URL}/?date=${date}</loc>\n`;
        sitemapContent += `      <lastmod>${date}</lastmod>\n`;
        sitemapContent += `      <changefreq>never</changefreq>\n`;
        sitemapContent += `      <priority>0.8</priority>\n`;
        sitemapContent += `   </url>\n`;
    });

    sitemapContent += `</urlset>`;
    fs.writeFileSync(SITEMAP_FILE, sitemapContent);
    console.log(`✅ Sitemap generated with ${dates.length + 1} URLs!`);

    // ==========================================
    // PART 2: INJECT DYNAMIC SOCIAL THUMBNAILS
    // ==========================================
    let indexHtml = fs.readFileSync(INDEX_FILE, 'utf8');

    // Clean up old injected tags (so we don't accidentally stack them up)
    indexHtml = indexHtml.replace(/<!-- OG_TAGS_START -->[\s\S]*?<!-- OG_TAGS_END -->\n?/g, '');

    // Create the new meta tags pointing to today's image
    const ogTags = `<!-- OG_TAGS_START -->
    <meta property="og:title" content="Global News Digest | Latest Analysis" />
    <meta property="og:description" content="Daily AI-generated summaries of the world's most critical and controversial topics." />
    <meta property="og:image" content="${BASE_URL}/images/${latestDate}.png" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Global News Digest | Latest Analysis" />
    <meta name="twitter:description" content="Daily AI-generated summaries of the world's most critical and controversial topics." />
    <meta name="twitter:image" content="${BASE_URL}/images/${latestDate}.png" />
    <!-- OG_TAGS_END -->`;

    // Inject them right before the closing </head> tag
    indexHtml = indexHtml.replace('</head>', `${ogTags}\n</head>`);
    
    fs.writeFileSync(INDEX_FILE, indexHtml);
    console.log(`✅ Injected social thumbnail (${latestDate}.png) into index.html!`);

} catch (error) {
    console.error('❌ Error during build step:', error.message);
    process.exit(1);
}
